@startuml
' Las notificaiones con email real y demas sera para mas adelante
' Ahi si podria usar observer y strategy

class AppointmentController {
    + create()
}
AppointmentController --> IAppointmentService

interface IAppointmentService {
    + checkAvailability(professional_service, datetime_slot)
    + createAppointment(professional, client_id, datetime)
}
IAppointmentService --> Appointment

class AppointmentService implements IAppointmentService{
    - professional_service
    - appointment_repo

    + checkAvailability(professional, datetime_slot)
    + create_appointment()
}
AppointmentService o-- IAppointmentRepository
AppointmentService --> INotificationService
AppointmentService o-- IProfessionalService

interface IAppointmentRepository {
    + save(appointment)
    + find_by_professional_and_datetime(professional, datetime)
}
IAppointmentRepository --> Appointment
IAppointmentRepository ..> PendingState
IAppointmentRepository ..> CanceledState
IAppointmentRepository ..> ConfirmedState
IAppointmentRepository ..> PendingState

class AppointmentRepository implements IAppointmentRepository{
    + save(appointment)
    + find_by_professional_and_datetime(professional_id, datetime)
}
AppointmentRepository --> Connection

class Appointment {
    - id
    - duration
    - professional_id
    - client_id
    - state

    + Appointment()
    + changeState(state)
    + blocks_schedule()
}
Appointment o-- State

interface State {
    + blocks_schedule()
}

class PendingState implements State{
    - appointment

    + setAppointment(appointment)
    + blocks_schedule()
}

class ConfirmedState implements State{
    - appointment

    + setAppointment(appointment)
    + blocks_schedule()
}

class CanceledState implements State{
    - appointment

    + setAppointment(appointment)
    + blocks_schedule()
}

class CompletedState implements State{
    - appointment

    + setAppointment(appointment)
    + blocks_schedule()
}

class Connection {
    - instance: Connection 

    - Connection()
    + getInstance():Connection
}

interface INotificationService {
    + sendConfirmation()
}

class NotificationService implements INotificationService {
    + sendConfirmation()
}

class Professional{
    - id
    - name 
    - specialty
    - working_hours:{}
    - default_duration_minutes
}

class ProfessionalController {
    + create()
}
ProfessionalController --> IProfessionalService

interface IProfessionalService {
    + create_professional()
    + get_by_id(professional_id)
    + check_working_hours(professional, datetime)
}
IProfessionalService --> Professional

class ProfessionalService implements IProfessionalService {
    + create_professional()
    + get_by_id(professional_id)
    + check_working_hours(professional, datetime)
}
ProfessionalService --> IProfessionalRepository

interface IProfessionalRepository {
    + save()
}
IProfessionalRepository --> Professional

class ProfessionalRepository implements IProfessionalRepository {
    + save()
}

@enduml